version: "3"
services:
  product-service:
    build: ./build
    volumes:
      - repo:/usr/local/
      
  tomcat:
    image: tomcat:9.0-jdk8-adoptopenjdk-hotspot
    depends_on:
      - "product-service"
    ports:
      - 8080:8080
    volumes:
      - repo:/usr/local/tomcat/webapps
      
volumes:
  repo: